### ISSUE TITLE
Error 500 with AwsS3Storage and non-URL-encoded characters in path

### ISSUE THREAD

**Issue by krizalys** [krizalys/cachine#1]
Requesting a file whose path contains a non-URL-encoded special character, such as `%` (from a `%20` in the URL) returns an error 500 with AwsS3Storage and non-URL-encoded characters in path.

The trace is as follows:

```
TypeError: Request path contains unescaped characters
   at new ClientRequest (_http_client.js:53:11)
   at Object.exports.request (http.js:31:10)
   at Object.AwsS3Storage.StaticHostingReadStrategy.stat (/path/to/app/node_modules/cachine/lib/storage/AwsS3Storage.js:169:30)
   at AwsS3Storage.stat (/path/to/app/node_modules/cachine/lib/storage/AwsS3Storage.js:59:14)
   at Cachine.request (/path/to/app/node_modules/cachine/lib/Cachine.js:101:28)
   at app.get (/path/to/app/server.js:61:32)
   at Layer.handle [as handle_request] (/path/to/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/path/to/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/path/to/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/path/to/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by krizalys** [comment]
Resolved in https://github.com/krizalys/cachine/pull/2
